services:
    ussd_callback:
        build: ./ussd_callback
        volumes:
          - ./logs:/app/logs
          - sqlite_data:/app/data
        environment:
          - FLASK_ENV=production
          - SECRET_KEY=your_secure_secret_key_here
          - DATABASE_URL=sqlite:///data/govwatch.db
          - LOG_LEVEL=INFO
        restart: always

volumes:
    sqlite_data:
      name: govwatch-sqlite-data