services:
    app_service:
      build: app-service
      environment:
          - NODE_ENV=production
    ussd_callback:
        build: ./ussd_callback
        volumes:
          - ./logs:/app/logs
        environment:
          - FLASK_ENV=production
          - SECRET_KEY=your_secure_secret_key_here
#          - DATABASE_URL=sqlite:///data/govwatch.db
          - DATABASE_URL=${DB_URI}
          - LOG_LEVEL=INFO
        restart: always